UserProfile/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from UserProfile.views import(
    registrations,
    login,
    index,
    logout_view,
    user_profile,
    update_profile,
    search_donor,
    About_Blood,
    )

app_name='UserProfile'

urlpatterns = [
    path('', index, name='index'),
    path('registrations/', registrations, name='registrations'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('User/<str:username>', user_profile, name='user_profile'),
    path('update_profile/<str:username>', update_profile, name='update_profile'),
    path('search_donor/', search_donor, name='search_donor'),
    path('About_Blood/', About_Blood, name='About_Blood'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserProfile.urls')),
    path('', include('articals.urls')),
]

UserProfile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField, DateField

# Create your models here.
class UserProfile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic=models.ImageField(
        upload_to="UserProfile/Profilepic/", 
        default='UserProfile/Profilepic/default_user_profile.png'
        )
    phone=models.CharField(max_length=20)
    DateOfBirth=DateField(max_length=50)
    profession=CharField(max_length=50)
    bloodGroup=CharField(max_length=20)
    gender=CharField(max_length=20)
    city=CharField(max_length=30)
    thana=CharField(max_length=30)
    union=CharField(max_length=30)
    postCode=CharField(max_length=20)
    otp=models.CharField(max_length=30)
    published = models.BooleanField(default=True)


    def __str__(self) -> str:
        return self.user.username

UserProfile/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.urls import reverse_lazy
from django.shortcuts import HttpResponse
from django.contrib.auth import logout, authenticate, login as auth_login
from django.contrib.auth.models import User
from UserProfile.models import UserProfile
import random



def index(request):    
    title = {'title': "Home"}
    return render(request, 'index.html', title)


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        valid_user = authenticate(
            request, username=username, password=password)
        if valid_user is not None:
            auth_login(request, valid_user)
            return redirect(reverse_lazy('UserProfile:index'))
        else:
            return HttpResponse("wrong informations")

    return render(request, 'UserProfile/login.html')


def logout_view(request):
    logout(request)
    return redirect(reverse_lazy('UserProfile:index'))



def registrations(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        username = request.POST.get('username')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        Password = request.POST.get('password')
        Password2 = request.POST.get('password2')
        DateOfBirth = request.POST.get('DateOfBirth')
        profession = request.POST.get('profession')
        bloodGroup = request.POST.get('bloodGroup')
        gender = request.POST.get('gender')
        city = request.POST.get('city')
        thana = request.POST.get('thana')
        union = request.POST.get('union')
        postCode = request.POST.get('postCode')
        # bio=" "

        check_user = User.objects.filter(email=email).first()
        check_profile = UserProfile.objects.filter(phone=phone).first()

        if Password != Password2:
            context1 = {"message1": "Password mismatch", "class1": "danger"}
            return render(request, 'UserProfile/registration.html', context1)

        if check_user or check_profile:
            context = {"message": "User already exist", "class": "danger"}
            return render(request, 'UserProfile/registration.html', context)

        user = User.objects.create_user(
            first_name=fname, last_name=lname, username=username, email=email, password=Password)
        user.save()

        profile= UserProfile(user=user,
                              phone=phone, DateOfBirth=DateOfBirth,
                              profession=profession,
                              bloodGroup=bloodGroup,
                              gender=gender,
                              city=city,
                              thana=thana,
                              union=union,
                              postCode=postCode,
        )
        profile.save()

        context = {"message": "Successfully registrations Complate",
                    "class2":"alert1 success ",
                   }
        return render(request, 'UserProfile/login.html', context)

    return render(request, 'UserProfile/registration.html')

def user_profile(request,username):
    user_information=get_list_or_404(User, username=username)
    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_profile_info=UserProfile.objects.get(user__pk=user_id)
        img=user_profile_info.profile_pic
        print(img)

    context={"title":"Profile", "user_information":user_information,"user_profile_info":user_profile_info}

    return render(request, 'UserProfile/Profile.html', context)


def update_profile(request,username):
    user_information=get_list_or_404(User, username=username)
    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_profile_info=UserProfile.objects.get(user__pk=user_id)
        user_profile_info_id=user_profile_info.id

    if(request.method=="POST" and request.FILES):
        username=request.POST.get("username")
        phone=request.POST.get("phone")
        bio=request.POST.get("bio")
        city=request.POST.get("address")
        profile_picture=request.FILES['profile_picture']

        User_Profile=UserProfile(user=current_user, profile_pic=profile_picture)
        User_Profile.save()
        User.objects.filter(id=user_id).update(username=username)
        UserProfile.objects.filter(pk=user_profile_info_id).update(
            phone=phone,
            city=city,
            )
        return redirect(reverse_lazy('UserProfile:index'))

    context={"title":"Profile", "user_information":user_information,"user_profile_info":user_profile_info}
    return render(request, 'UserProfile/UpdateProfile.html',context)


def search_donor(request):
    userprofile=UserProfile.objects.all()
    if request.method=="POST":
        blood_group=request.POST.get("blood")
        location=request.POST.get("location")
        
        userprofile=UserProfile.objects.filter(
            bloodGroup__contains=blood_group,
            city__contains=location,
        )

        context={'userprofile':userprofile}
        return render(request, 'UserProfile/search.html',context)
    context={'userprofile':userprofile}
    return render(request, 'UserProfile/search.html',context)


def About_Blood(request):
    title = {'title': "About Blood"}
    return render(request, 'about_blood.html',title)

templates/UserProfile/Profile.html
{%extends 'base.html'%} 

{%block head%} 

{% load static %}
<!-- Main css -->
<link rel="stylesheet" href="{%static 'UserProfile/css/style.css'%}" />
{%endblock%} 

{%block body%}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row d-flex justify-content-center">
            <div class="col-xl-12 col-md-12 ">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25"> 
                                    <!-- <img style="height:100px; width:100px;" src=" {%static 'UserProfile/images/profile.png'%}" class="img-radius" alt="User-Profile-Image"> -->
                                    <img style="height:100px; width:100px;" src="{{user_profile_info.profile_pic.url}}" class="img-radius" alt="User-Profile-Image">
                                    <!-- {% if user_profile_info.profile_pic %}
                                    <img src="media/{{user_profile_info.profile_pic}}" class="img-radius" alt="User-Profile-Image">
                                    {% else %}
                                    <img src="DEFAULT_IMAGE" class="img-radius" alt="User-Profile-Image">
                                    {% endif %} -->
                                </div>
                                <h6 class="f-w-600">{{user.username}}</h6>
                                <p>{{user_profile_info.bio}}</p>
                                <div class="pt-3">
                                    <a class="myButton btn-primary" href="{% url 'UserProfile:update_profile' username=request.user.username%}">Update Profile</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Personal Information</h6>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">{{user.email}}</h6>
                                    </div>
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Phone</p>
                                        <h6 class="text-muted f-w-400">{{user_profile_info.phone}}</h6>
                                    </div>
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Blood Group</p>
                                        <h4 class="f-w-400 text-danger">{{user_profile_info.bloodGroup}}</h4>
                                    </div>
                                </div>
                                <div class="row pt-4">
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Date Of Borth</p>
                                        <h6 class="text-muted f-w-400">{{user_profile_info.DateOfBirth}}</h6>
                                    </div>
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Gender</p>
                                        <h6 class="text-muted f-w-400">{{user_profile_info.gender}}</h6>
                                    </div>
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Address</p>
                                        <h6 class="text-muted f-w-400">{{user_profile_info.union}},{{user_profile_info.thana}},{{user_profile_info.city}}</h6>
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Others Informations.</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <form action="" method="post">
                                            <div class="col-sm-6 col-md-6 col-lg-6">
                                                <input type="text" name="donate_date" placeholder="Last Donate Date" class="form-control p-1 pl-3" id="inputfname" autofocus/>
                                            </div>
                                            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6 pt-3 pb-4">
                                                <button type="submit" class="btn btn-primary float-start myButton">Add</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Last Donate</p>
                                        <h6 class="text-muted f-w-400">01-12-2021</h6>
                                    </div>
                                </div>
                                <ul class="social-link list-unstyled m-t-40 m-b-10">
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/UserProfile/UpdateProfile.html
{% extends 'base.html' %} {% block head %} {% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'UserProfile/css/updateprofile.css' %}"> {% endblock %} {% block body%}
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row updateprofile">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" src="{{user_profile_info.profile_pic.url}}" width="90">
                <span class="font-weight-bold pt-3">{{user.username}}</span>
                <span class="text-black-50">{{user_info.email}}</span>
                <span>{{user_info.profile.country}}</span></div>
        </div>

        <div class="col-md-5 border-right">
            <form action="{% url 'UserProfile:update_profile' username=request.user.username%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- enctype="multipart/form-data" -->
                <div class=" text-center">
                    <h3 class="text-center text-info pt-2">Edit Your Profile</h3>
                </div>
                <hr>
                <div class="p-3">
                    <div class="row mt-2">
                        <div class="col-md-12">
                            <label class="labels">User Name</label>
                            <input name='username' type="text" class="form-control" placeholder="UserName" value="{{user.username}}">
                        </div>
                        <div class="col-md-12">
                            <label class="labels">Phone</label>
                            <input name='phone' type="text" class="form-control" placeholder="" value="{{user_profile_info.phone}}">
                        </div>
                        <!-- <div class="col-md-12">
                                    <label class="labels">Bio</label>
                                    <input name='bio' type="text" class="form-control" placeholder="" value="{{user_profile_info.bio}}">
                                </div> -->
                        <div class="col-md-12">
                            <label class="labels">Location</label>
                            <input name='address' type="text" class="form-control" placeholder="UserName" value="{{user_profile_info.city}}">
                        </div>
                        <div class="col-md-12">
                            <label class="labels">Profile Picture</label>
                            <input name='profile_picture' type="file" class="form-control" placeholder="UserName">
                        </div>
                    </div>

                    <div class="mt-5 text-center">
                        <input type="submit" class="btn btn-primary profile-button" value="save">
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-4">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center experience"><span>Edit Experience</span><span class="border px-3 p-1 add-experience"><i class="fa fa-plus"></i>&nbsp;Experience</span></div>
                <div class="d-flex flex-row mt-3 exp-container"><img src="https://i.imgur.com/azSfBM3.png" width="45" height="45">
                    <div class="work-experience ml-1"><span class="font-weight-bold d-block">Senior UI/UX Designer</span><span class="d-block text-black-50 labels">Twitter Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
                </div>
                <hr>
                <div class="d-flex flex-row mt-3 exp-container"><img src="https://img.icons8.com/color/100/000000/facebook.png" width="45" height="45">
                    <div class="work-experience ml-1"><span class="font-weight-bold d-block">Senior UI/UX Designer</span><span class="d-block text-black-50 labels">Facebook Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
                </div>
                <hr>
                <div class="d-flex flex-row mt-3 exp-container"><img src="https://img.icons8.com/color/50/000000/google-logo.png" width="45" height="45">
                    <div class="work-experience ml-1"><span class="font-weight-bold d-block">UI/UX Designer</span><span class="d-block text-black-50 labels">Google Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
                </div>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"> {% endblock %}

templates/UserProfile/login.html
{%extends 'base.html'%} {%block head%} {% load static %}
<!-- Main css -->
<link rel="stylesheet" href="{%static 'UserProfile/css/style.css'%}" />
{%endblock%} {%block body%}
<section class="sign-in">
    <div class="container">
        <div class="login_form">
            <div class=" {{class2}} {{class}} ">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{message}}
            </div>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-5">
                    <img src="{%static 'base/images/signin-image.jpg'%}" alt="sing up image" />
                </div>
                <div class="col-lg-7 col-md-7 col-sm-7">
                    <form action="{% url 'UserProfile:login'%}" method="post" class="row g-3">
                        {% csrf_token %}
                        <h3>Sign into your account</h3>
                        <span class="notice-1">Give blood, Take blood & Save life</span>
                        <!-- <center><span class="text-{{class}} bg-info">sdfgdsfg</span></center> -->
                        <div class="">
                            <input
                                name="username"
                                type="text"
                                class="form-control"
                                placeholder="Enter your user Name"
                                id="exampleInputEmail1"
                                aria-describedby="emailHelp"
                                required
                            />
                        </div>
                        <div class="">
                            <input
                                name="password"
                                type="password"
                                class="form-control"
                                placeholder="Enter your password"
                                id="exampleInputPassword1"
                            />
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                        <a class="small text-muted" href="#!">Forgot password?</a>
                        <p class="mb-5 pb-lg-2" style="color: #393f81">
                            Don't have an account?
                            <a href="{% url 'UserProfile:registrations'%}" style="color: #393f81"> Register here </a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{%endblock%}

templates/UserProfile/registration.html
{%extends 'base.html'%} {%block head%} {% load static %}
<link rel="stylesheet" href="{% static 'UserProfile/css/style.css' %}" />
{%endblock%} {%block body%}
<div class="registration_form">
    <h3>New Account</h3>
    <h5 class="pb-3">Give blood, Take blood & Save life</h5>
    <form action="{% url 'UserProfile:registrations'%}" method="post" class="row g-3">
        {% csrf_token %}
        <div class="col-lg-12 col-md-6 col-sm-6">
            <center><span class="text-{{class}}">{{message}}</span></center>
        </div>
        <div class="col-md-6">
            <input type="text" name="fname" placeholder="Fast Name" class="form-control" id="inputfname" autofocus/>
        </div>
        <div class="col-md-6">
            <input type="text" name="lname" placeholder="last Name" class="form-control" id="inputlname" />
        </div>
        <div class="col-md-6">
            <input type="text" name="username" placeholder="User Name" class="form-control" id="inputfname" required/>
        </div>
        <div class="col-md-6">
            <input type="number" name="phone" placeholder="Phone" class="form-control" id="inputPhone" />
        </div>
        <div class="col-md-6">
            <input type="email" name="email" placeholder="Email" class="form-control" id="inputEmail4" />
        </div>
        <div class="col-md-6">
            <input type="password" name="password" placeholder="Password" class="form-control" id="inputEmail4" />
        </div>
        <div class="col-md-6">
            <input
                type="password"
                name="password2"
                placeholder="Confirm Password"
                class="form-control"
                id="inputPassword4"
            />
            <span class="text-{{class1}}">{{message1}}</span>
        </div>
        <div class="col-md-6">
            <input type="date" name="DateOfBirth" class="form-control" id="inputDate" />
        </div>
        <div class="col-md-6">
            <select name="profession" class="form-select" aria-label="Default select example">
                <option selected>Profession</option>
                <option value="Student">Student</option>
                <option value="Doctor">Doctor</option>
                <option value="Nurse">Nurse</option>
                <option value="Teacher">Teacher</option>
                <option value="Job">Job</option>
            </select>
        </div>
        <div class="col-md-6">
            <select name="bloodGroup" class="form-select" aria-label="Default select example">
                <option selected>Blood Group</option>
                <option value="A+">A+</option>
                <option value="AB">AB</option>
                <option value="AB+">AB+</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="O">O-</option>
            </select>
        </div>
        <div class="col-md-6">
            <select name="gender" class="form-select" aria-label="Default select example">
                <option selected>Gender</option>
                <option value="Male">Male</option>
                <option value="Femel">Femel</option>
                <option value="Others">Others</option>
            </select>
        </div>
        <div class="col-md-6">
            <select name="city" class="form-select" aria-label="Default select example">
                <option selected>Select City</option>
                <option value="Dhaka">Dhaka</option>
                <option value="Rangpur">Rangpur</option>
                <option value="Rajshahi">Rajshahi</option>
                <option value="Comilla">Comilla</option>
                <option value="Borisal">Borisal</option>
                <option value="Khulna">Khulna</option>
                <option value="Mymensingh">Mymensingh</option>
                <option value="Sylhet">Sylhet</option>
            </select>
        </div>
        <div class="col-md-6">
            <input type="text" placeholder="Thana" name="thana" class="form-control" id="inputlname" />
        </div>
        <div class="col-md-6">
            <input type="text" placeholder="Union" name="union" class="form-control" id="inputfname" />
        </div>
        <div class="col-md-6">
            <input type="text" placeholder="Post Code" name="postCode" class="form-control" id="inputlname" />
        </div>
        <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
            <p class="notice text-danger">
                ** All data keeps secret except contacts info thats are not problem at all.
            </p>
        </div>
        <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6 pt-3 pb-2">
            <button type="submit" class="btn btn-primary float-end myButton">Create Account</button>
        </div>
    </form>
</div>
{%endblock%}