UserProfile/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from UserProfile.views import(
    registrations,
    login,
    index,
    logout_view,
    user_profile,
    update_profile,
    search_donor,
    About_Blood,
    )

app_name='UserProfile'

urlpatterns = [
    path('', index, name='index'),
    path('registrations/', registrations, name='registrations'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('User/<str:username>', user_profile, name='user_profile'),
    path('update_profile/<str:username>', update_profile, name='update_profile'),
    path('search_donor/', search_donor, name='search_donor'),
    path('About_Blood/', About_Blood, name='About_Blood'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articals/urls.py
from django.contrib import admin
from django.urls import path
from articals.views import(
    articals_index,
    request_blood_post
    )

app_name='articals'

urlpatterns = [
    path('post/', articals_index, name='articals_index'),
    path('request_blood/', request_blood_post, name='request_blood_post'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserProfile.urls')),
    path('', include('articals.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{title}}</title>
    {% load static %}
    <link rel="icon" href="{%static 'base/images/233_-_blood-512.png'%}" /> {%block head%} {%endblock%}
    <link rel="icon" href="Img/233_-_blood-512.png" />
    <!---------------------------------------------bootstrap icon cdn-------------------------------------->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css" />
    <!---------------------------------------------bootstrap cdn------------------------------------------>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <!--------------------------------------------main css------------------------------------------------->
    {% load static %}
    <link rel="stylesheet" href="{%static 'base/css/style.css'%}" />
</head>

<body class="body">
    <div class="header-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 mail-main">
                    <div class="mail">
                        <div class="mail-icon">
                            <i class="bi bi-envelope"></i>
                        </div>
                        <span>blooddonate@gmail.com</span>
                    </div>

                    <div class="phone">
                        <div class="phone-icon">
                            <i class="bi bi-telephone"></i>
                        </div>
                        <span>01712-141415</span>
                    </div>
                </div>
                {% if request.user.is_authenticated %} {% else %}
                <div class="col-lg-6 col-md-6 col-sm-12 reg-main">
                    <a href="{%url 'UserProfile:registrations'%}" class="btn reg-btn float-end" type="submit">Registration</a>
                </div>
                {%endif%}
            </div>
        </div>
    </div>

    <!----------------------------------------------------------------------------------------------
                                                                Navbar
    ----------------------------------------------------------------------------------------------->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="{%static 'base/images/logo_white.png'%}" alt="#" width="100%" height="45px">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'UserProfile:About_Blood'%}">About Blood</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'UserProfile:search_donor'%}">Search Donor</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'articals:articals_index'%}">Community Post</a>
                    </li>
                    {%endif%}
                    <li class="nav-item dropdown">
                        {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="user_profile_image" src="{%static 'UserProfile/images/profile.png'%}" alt="">
                            <!-- <img class="user_profile_image" src="media/{{user_profile_info.profile_pic}}" alt=""> -->
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{%url 'UserProfile:user_profile' username=request.user.username%}">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="{%url 'UserProfile:logout'%}" type="submit">
                                        Logout 
                                    </a>
                            </li>
                        </ul>
                        {% else %}
                        <form class="d-flex login_button">
                            <a href="{%url 'UserProfile:login'%}" class="btn btn-outline-success" type="submit">
                                    Login
                                </a>
                        </form>
                        {%endif%}
                    </li>
                </ul>
                <form class="d-flex">
                    <!-- <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="user_profile_image" src="{%static 'UserProfile/images/profile.png'%}" alt="">
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                          <li><button class="dropdown-item" type="button">
                                <a href="{%url 'UserProfile:logout'%}"  type="submit">
                                    Logout 
                                </a>
                          </button></li>
                          <li><button class="dropdown-item" type="button">My Account</button></li>
                        </ul>
                      </div> -->
                </form>
            </div>
        </div>
    </nav>
    <!----------------------------------------------------------------------------------------------
                                        Body contant
        ----------------------------------------------------------------------------------------------->
    {%block body%} {%endblock%}



    <!------------------------------------------------------------------------------------------------------
                                                                    section 8
        -------------------------------------------------------------------------------------------------------->

    <div class="footer">
        <div class="container">
            <div class="footer_first">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-12 footer_first_left">
                        <h3>Emergency Call</h3>
                        <p>+8801712-141415</p>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 footer_first_middle ">
                        <h3>Email For Contact</h3>
                        <p>blooddonate@gmail.com</p>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 footer_first_right">
                        <h3>Contact us Social Media</h3>
                        <div class="footer_social_icon">
                            <div class="twitter">
                                <a href="">
                                    <i class="fab fa-twitter fa-twitters"></i>
                                </a>
                            </div>

                            <div class="facebook">
                                <a href="">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                            </div>

                            <div class="linkedin">
                                <a href="">
                                    <i class="fab fa-linkedin-in"></i>
                                </a>
                            </div>

                            <div class="whatsapp">
                                <a href="">
                                    <i class="fab fa-whatsapp"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                    <!-- <center> -->
                    <div class="line">
                    </div>
                    <!-- </center> -->

                </div>
            </div>

            <div class="footer_last">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-12 footer_last_left">
                        <div class="footer_logo">
                            <img src="{%static 'base/images/logo_white.png'%}" alt="Footer Logo">
                            <p>The Blood Connection is a non-profit organization. Whole Blood can be donated every 56 days. Donors must be 16 or older to donate. The blood connection is an automated blood service that connects blood searchers with blood
                                donors in a moment through SMS and website.</p>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-12 footer_last_middle">
                        <h3>Quick Links</h3>
                        <div class="quick_links_line"></div>
                        <div class="footer_menu">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About Blood</a></li>
                            <li><a href="#">Search Donor</a></li>
                            <li><a href="#">Community Post</a></li>
                            <li><a href="#team">Our Team</a></li>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-12 footer_last_right">
                        <h3>Photo Gallery</h3>
                        <div class="photo_gallery_line"></div>
                        <div class="gallery">
                            <img src="{%static 'base/images/g1.png'%}" alt="Gallery Pic-1">
                            <img src="{%static 'base/images/g2.png'%}" alt="Gallery Pic-3">
                            <img src="{%static 'base/images/g3.png'%}" alt="Gallery Pic-2">
                            <img src="{%static 'base/images/g4.png'%}" alt="Gallery Pic-4">
                            <img src="{%static 'base/images/g5.png'%}" alt="Gallery Pic-5">
                            <img src="{%static 'base/images/g6.png'%}" alt="Gallery Pic-6">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer_reserve_part text-center">
            <p>@2021 Blood Connection All Right Reserved </p>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>

</html>